apiVersion: v1
kind: Service
metadata:
  labels:
    app: backend-redis
  name: backend-redis
spec:
  ports:
  - port: 6379
    protocol: TCP
    targetPort: 6379
  selector:
    app: backend-redis
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: backend-master
    role: service
  name: backend-redis-master
spec:
  ports:
  - port: 6379
    protocol: TCP
    targetPort: 6379
  selector:
    backend-redis-master: "true"
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: backend-sentinel
    role: backend-service
  name: backend-redis-sentinel
spec:
  ports:
  - port: 26379
    protocol: TCP
    targetPort: 26379
  selector:
    backend-redis-sentinel: "true"
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
